# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pegasus_messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pegasus_messages.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x16pegasus_messages.proto\"\xa9\x01\n\x07Request\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x19\n\x07\x63ommand\x18\x02 \x01(\x0e\x32\x08.Command\x12\x12\n\ncommand_id\x18\x03 \x01(\x04\x12\x16\n\x0cplace_holder\x18\n \x01(\x08H\x00\x12\x12\n\x08\x61ltitude\x18\x0b \x01(\x02H\x00\x12\x14\n\npose_index\x18\x0c \x01(\rH\x00\x12\x12\n\x08req_data\x18\r \x01(\x0cH\x00\x42\x06\n\x04\x64\x61ta\"\xc2\x01\n\rHeartBeatData\x12(\n\x0f\x63ommander_state\x18\x01 \x01(\x0e\x32\x0f.CommanderState\x12\x12\n\ncommand_id\x18\x02 \x01(\x04\x12\x18\n\x10\x63ommand_complete\x18\x03 \x01(\x08\x12\x14\n\x0cmavros_state\x18\x04 \x01(\x0c\x12\x1a\n\x12\x62\x61selink_transform\x18\x05 \x01(\x0c\x12\x12\n\nlocal_pose\x18\x06 \x01(\x0c\x12\x13\n\x0bgps_nav_sat\x18\x07 \x01(\x0c\"\xac\x01\n\x05Reply\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x17\n\x06status\x18\x02 \x01(\x0e\x32\x07.Status\x12\x1b\n\x07\x63ommand\x18\n \x01(\x0e\x32\x08.CommandH\x00\x12\x14\n\npose_index\x18\x0b \x01(\rH\x00\x12(\n\x0eheartbeat_data\x18\x0c \x01(\x0b\x32\x0e.HeartBeatDataH\x00\x12\x12\n\x08rep_data\x18\r \x01(\x0cH\x00\x42\x06\n\x04\x64\x61ta*\x93\x01\n\x07\x43ommand\x12\x10\n\x0cNONE_COMMAND\x10\x00\x12\x10\n\x0cSET_OFFBOARD\x10\x01\x12\x16\n\x12SET_RETURN_TO_HOME\x10\x02\x12\x0b\n\x07SET_ARM\x10\x03\x12\x0c\n\x08TAKE_OFF\x10\x04\x12\x0c\n\x08SET_PATH\x10\x05\x12\x13\n\x0fGOTO_POSE_INDEX\x10\x06\x12\x0e\n\nHEART_BEAT\x10\x07*b\n\x06Status\x12\x0f\n\x0bNONE_STATUS\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x0b\n\x07\x46\x41ILURE\x10\x02\x12\x16\n\x12POSE_INDEX_REACHED\x10\x03\x12\x15\n\x11HEART_BEAT_STATUS\x10\x04*q\n\x0e\x43ommanderState\x12\x08\n\x04IDLE\x10\x00\x12\x0e\n\nPREP_STATE\x10\x01\x12\x11\n\rOFFBOARD_MODE\x10\x02\x12\n\n\x06\x41RMING\x10\x03\x12\t\n\x05HOVER\x10\x04\x12\x07\n\x03RUN\x10\x05\x12\x12\n\x0eRETURN_TO_HOME\x10\x06\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_COMMAND = _descriptor.EnumDescriptor(
  name='Command',
  full_name='Command',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE_COMMAND', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SET_OFFBOARD', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SET_RETURN_TO_HOME', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SET_ARM', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TAKE_OFF', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SET_PATH', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GOTO_POSE_INDEX', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HEART_BEAT', index=7, number=7,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=571,
  serialized_end=718,
)
_sym_db.RegisterEnumDescriptor(_COMMAND)

Command = enum_type_wrapper.EnumTypeWrapper(_COMMAND)
_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE_STATUS', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILURE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POSE_INDEX_REACHED', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HEART_BEAT_STATUS', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=720,
  serialized_end=818,
)
_sym_db.RegisterEnumDescriptor(_STATUS)

Status = enum_type_wrapper.EnumTypeWrapper(_STATUS)
_COMMANDERSTATE = _descriptor.EnumDescriptor(
  name='CommanderState',
  full_name='CommanderState',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='IDLE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PREP_STATE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OFFBOARD_MODE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ARMING', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HOVER', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUN', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RETURN_TO_HOME', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=820,
  serialized_end=933,
)
_sym_db.RegisterEnumDescriptor(_COMMANDERSTATE)

CommanderState = enum_type_wrapper.EnumTypeWrapper(_COMMANDERSTATE)
NONE_COMMAND = 0
SET_OFFBOARD = 1
SET_RETURN_TO_HOME = 2
SET_ARM = 3
TAKE_OFF = 4
SET_PATH = 5
GOTO_POSE_INDEX = 6
HEART_BEAT = 7
NONE_STATUS = 0
SUCCESS = 1
FAILURE = 2
POSE_INDEX_REACHED = 3
HEART_BEAT_STATUS = 4
IDLE = 0
PREP_STATE = 1
OFFBOARD_MODE = 2
ARMING = 3
HOVER = 4
RUN = 5
RETURN_TO_HOME = 6



_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Request.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='command', full_name='Request.command', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='command_id', full_name='Request.command_id', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='place_holder', full_name='Request.place_holder', index=3,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='altitude', full_name='Request.altitude', index=4,
      number=11, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pose_index', full_name='Request.pose_index', index=5,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='req_data', full_name='Request.req_data', index=6,
      number=13, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data', full_name='Request.data',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=27,
  serialized_end=196,
)


_HEARTBEATDATA = _descriptor.Descriptor(
  name='HeartBeatData',
  full_name='HeartBeatData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='commander_state', full_name='HeartBeatData.commander_state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='command_id', full_name='HeartBeatData.command_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='command_complete', full_name='HeartBeatData.command_complete', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mavros_state', full_name='HeartBeatData.mavros_state', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='baselink_transform', full_name='HeartBeatData.baselink_transform', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='local_pose', full_name='HeartBeatData.local_pose', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gps_nav_sat', full_name='HeartBeatData.gps_nav_sat', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=393,
)


_REPLY = _descriptor.Descriptor(
  name='Reply',
  full_name='Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Reply.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='Reply.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='command', full_name='Reply.command', index=2,
      number=10, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pose_index', full_name='Reply.pose_index', index=3,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='heartbeat_data', full_name='Reply.heartbeat_data', index=4,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rep_data', full_name='Reply.rep_data', index=5,
      number=13, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data', full_name='Reply.data',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=396,
  serialized_end=568,
)

_REQUEST.fields_by_name['command'].enum_type = _COMMAND
_REQUEST.oneofs_by_name['data'].fields.append(
  _REQUEST.fields_by_name['place_holder'])
_REQUEST.fields_by_name['place_holder'].containing_oneof = _REQUEST.oneofs_by_name['data']
_REQUEST.oneofs_by_name['data'].fields.append(
  _REQUEST.fields_by_name['altitude'])
_REQUEST.fields_by_name['altitude'].containing_oneof = _REQUEST.oneofs_by_name['data']
_REQUEST.oneofs_by_name['data'].fields.append(
  _REQUEST.fields_by_name['pose_index'])
_REQUEST.fields_by_name['pose_index'].containing_oneof = _REQUEST.oneofs_by_name['data']
_REQUEST.oneofs_by_name['data'].fields.append(
  _REQUEST.fields_by_name['req_data'])
_REQUEST.fields_by_name['req_data'].containing_oneof = _REQUEST.oneofs_by_name['data']
_HEARTBEATDATA.fields_by_name['commander_state'].enum_type = _COMMANDERSTATE
_REPLY.fields_by_name['status'].enum_type = _STATUS
_REPLY.fields_by_name['command'].enum_type = _COMMAND
_REPLY.fields_by_name['heartbeat_data'].message_type = _HEARTBEATDATA
_REPLY.oneofs_by_name['data'].fields.append(
  _REPLY.fields_by_name['command'])
_REPLY.fields_by_name['command'].containing_oneof = _REPLY.oneofs_by_name['data']
_REPLY.oneofs_by_name['data'].fields.append(
  _REPLY.fields_by_name['pose_index'])
_REPLY.fields_by_name['pose_index'].containing_oneof = _REPLY.oneofs_by_name['data']
_REPLY.oneofs_by_name['data'].fields.append(
  _REPLY.fields_by_name['heartbeat_data'])
_REPLY.fields_by_name['heartbeat_data'].containing_oneof = _REPLY.oneofs_by_name['data']
_REPLY.oneofs_by_name['data'].fields.append(
  _REPLY.fields_by_name['rep_data'])
_REPLY.fields_by_name['rep_data'].containing_oneof = _REPLY.oneofs_by_name['data']
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['HeartBeatData'] = _HEARTBEATDATA
DESCRIPTOR.message_types_by_name['Reply'] = _REPLY
DESCRIPTOR.enum_types_by_name['Command'] = _COMMAND
DESCRIPTOR.enum_types_by_name['Status'] = _STATUS
DESCRIPTOR.enum_types_by_name['CommanderState'] = _COMMANDERSTATE

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'pegasus_messages_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  ))
_sym_db.RegisterMessage(Request)

HeartBeatData = _reflection.GeneratedProtocolMessageType('HeartBeatData', (_message.Message,), dict(
  DESCRIPTOR = _HEARTBEATDATA,
  __module__ = 'pegasus_messages_pb2'
  # @@protoc_insertion_point(class_scope:HeartBeatData)
  ))
_sym_db.RegisterMessage(HeartBeatData)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), dict(
  DESCRIPTOR = _REPLY,
  __module__ = 'pegasus_messages_pb2'
  # @@protoc_insertion_point(class_scope:Reply)
  ))
_sym_db.RegisterMessage(Reply)


# @@protoc_insertion_point(module_scope)
